### ISSUE TITLE
Problemas com o JSON

### ISSUE THREAD

**Issue by gabriel-brito** [iteliosbrasil/itelios-frontend-challenge#2]
Olá, tudo bem?!

Tenho de relatar um problema no JSON do teste.
O objeto imageName do JSON proposto vem com 2 barras na frente do link, impossibilitando o acesso a imagem do objeto principal. E, mesmo tirando as barras, o link do JSON leva a uma resposta 404. Segue o anexo:  

![404](https://user-images.githubusercontent.com/16655018/31520952-1338ff3e-af7e-11e7-8a09-b109c81c4607.JPG)

**Comment by feliperohde** [comment]
@gabriel-brito as duas barras no inicio da url está assim para que, se por ventura você use https em seu teste, as url de imagem continuem funcionando. 

você pode saber mais aqui:
http://blog.httpwatch.com/2010/02/10/using-protocol-relative-urls-to-switch-between-http-and-https/

**Comment by gabriel-brito** [comment]
Eu fui pensar nisso depois que mandei a issue e agora você me confirmou sobre xD
É que eu pensei que o erro estava por causa das barras, pois sempre utilizo o link absoluto.
Pode deixar que vou fazer uma leitura e analise do post que você me mandou! Valeu!
